import type { VideoResult } from "../types/contracts";
import { fmtTs } from "./time";

/** Markdown export with clickable youtu.be timestamp links —
 *  same output shape as the notebook's render cell. */
export function toMarkdown(r: VideoResult): string {
  const link = (s: number) => `[${fmtTs(s)}](https://youtu.be/${r.video_id}?t=${Math.floor(s)})`;
  const lines: string[] = [
    `# ${r.title}`,
    ``,
    `*${r.channel} · ${fmtTs(r.duration)} · transcript: ${r.transcript_source} · faithfulness ${(r.critic.faithfulness * 100).toFixed(0)}% (${r.critic.checked} claims checked)*`,
    ``,
    `## TL;DR`,
    ``,
    r.tldr,
    ``,
    `## Key takeaways`,
    ``,
    ...r.takeaways.map((t) => `- ${t}`),
    ``,
    `## Chapters`,
  ];
  for (const c of r.chapters) {
    lines.push(``, `### ${link(c.start)} ${c.title}`, ``, c.summary, ``);
    lines.push(...c.key_points.map((k) => `- ${k}`));
    if (c.evidence_timestamps.length) {
      lines.push(``, `Evidence: ${c.evidence_timestamps.map(link).join(" · ")}`);
    }
  }
  if (r.vision.length) {
    lines.push(``, `## On-screen evidence`, ``);
    for (const v of r.vision) {
      const text = v.ocr_text ? `\`${v.ocr_text}\`` : v.description;
      lines.push(`- ${link(v.timestamp)} **${v.frame_type}** — ${text}`);
    }
  }
  lines.push(``, `---`, `Generated by ClipSense.`);
  return lines.join("\n");
}

export function downloadMarkdown(r: VideoResult): void {
  const blob = new Blob([toMarkdown(r)], { type: "text/markdown;charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `clipsense-${r.video_id}.md`;
  a.click();
  URL.revokeObjectURL(a.href);
}
